/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SmsTermsRouteImport } from './routes/sms-terms'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ApiApplyRouteImport } from './routes/api/apply'
import { Route as ApiLeadRouteImport } from './routes/api/lead'
import { Route as ApiUnsubscribeRouteImport } from './routes/api/unsubscribe'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsTermsRoute = SmsTermsRouteImport.update({
  id: '/sms-terms',
  path: '/sms-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApplyRoute = ApiApplyRouteImport.update({
  id: '/api/apply',
  path: '/api/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadRoute = ApiLeadRouteImport.update({
  id: '/api/lead',
  path: '/api/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnsubscribeRoute = ApiUnsubscribeRouteImport.update({
  id: '/api/unsubscribe',
  path: '/api/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sms-terms': typeof SmsTermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/api/apply': typeof ApiApplyRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sms-terms': typeof SmsTermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/api/apply': typeof ApiApplyRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sms-terms': typeof SmsTermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/api/apply': typeof ApiApplyRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/contact'
    | '/privacy-policy'
    | '/sms-terms'
    | '/terms-of-service'
    | '/unsubscribe'
    | '/api/apply'
    | '/api/lead'
    | '/api/unsubscribe'
    | '/services/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/contact'
    | '/privacy-policy'
    | '/sms-terms'
    | '/terms-of-service'
    | '/unsubscribe'
    | '/api/apply'
    | '/api/lead'
    | '/api/unsubscribe'
    | '/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/contact'
    | '/privacy-policy'
    | '/sms-terms'
    | '/terms-of-service'
    | '/unsubscribe'
    | '/api/apply'
    | '/api/lead'
    | '/api/unsubscribe'
    | '/services/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  ContactRoute: typeof ContactRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SmsTermsRoute: typeof SmsTermsRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ApiApplyRoute: typeof ApiApplyRoute
  ApiLeadRoute: typeof ApiLeadRoute
  ApiUnsubscribeRoute: typeof ApiUnsubscribeRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms-terms': {
      id: '/sms-terms'
      path: '/sms-terms'
      fullPath: '/sms-terms'
      preLoaderRoute: typeof SmsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apply': {
      id: '/api/apply'
      path: '/api/apply'
      fullPath: '/api/apply'
      preLoaderRoute: typeof ApiApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead': {
      id: '/api/lead'
      path: '/api/lead'
      fullPath: '/api/lead'
      preLoaderRoute: typeof ApiLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unsubscribe': {
      id: '/api/unsubscribe'
      path: '/api/unsubscribe'
      fullPath: '/api/unsubscribe'
      preLoaderRoute: typeof ApiUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SmsTermsRoute: SmsTermsRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ApiApplyRoute: ApiApplyRoute,
  ApiLeadRoute: ApiLeadRoute,
  ApiUnsubscribeRoute: ApiUnsubscribeRoute,
  ServicesSlugRoute: ServicesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
